// scripts/generate-version.mjs
//
// Emits worker/version.generated.ts with the current commit SHA and
// build timestamp. Called automatically before `pnpm build` and
// `pnpm test` via the corresponding `pre*` hooks in package.json.
//
// Source of truth for the SHA, in priority order:
//   1. WORKERS_CI_COMMIT_SHA (Cloudflare Workers Builds)
//   2. CF_PAGES_COMMIT_SHA   (legacy Pages; CF Workers Builds also exports it for compat)
//   3. GITHUB_SHA            (GitHub Actions)
//   4. `git rev-parse HEAD`  (any local clone with .git/)
//   5. "dev"                 (fresh checkout without git, or running in a tarball)
//
// The generated file is committed with a placeholder value so the
// TypeScript graph remains importable on a fresh `pnpm install` and so
// tests run before any build step. CI (CF Workers Builds and GHA)
// re-runs this script before building so the deployed Worker always
// carries the real SHA + timestamp.

import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUTPUT = resolve(__dirname, "..", "worker", "version.generated.ts");

function resolveSha() {
  const envSha =
    process.env.WORKERS_CI_COMMIT_SHA || process.env.CF_PAGES_COMMIT_SHA || process.env.GITHUB_SHA;
  if (envSha) return envSha.trim();
  try {
    return execSync("git rev-parse HEAD", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "dev";
  }
}

const sha = resolveSha();
const builtAt = new Date().toISOString();

const content = `// Auto-generated by scripts/generate-version.mjs. DO NOT EDIT MANUALLY.
//
// The committed value of this file is a placeholder so that the
// TypeScript graph compiles on a fresh checkout. CI (CF Workers Builds
// + GitHub Actions) regenerates it before every build so the deployed
// Worker always reports the real commit SHA + build timestamp at
// GET /version.

export const COMMIT_SHA = ${JSON.stringify(sha)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
`;

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, content);

console.log(`[generate-version] wrote ${OUTPUT} (sha=${sha.slice(0, 7)}, builtAt=${builtAt})`);
