// Auto-generated by scripts/generate-version.mjs. DO NOT EDIT MANUALLY.
//
// The committed value of this file is a placeholder so that the
// TypeScript graph compiles on a fresh checkout. CI (CF Workers Builds
// + GitHub Actions) regenerates it before every build so the deployed
// Worker always reports the real commit SHA + build timestamp at
// GET /version.

export const COMMIT_SHA = "dev";
export const BUILT_AT = "1970-01-01T00:00:00.000Z";
